### ISSUE TITLE
Allow base_url to be overridden via attribute 

### ISSUE THREAD

**Issue by marcusn** [sous-chefs/packagecloud#38]
Allow base_url to be overridden via attribute. This is useful to point to a mirror globally in a private infrastructure.

**Comment by ice799** [comment]
Thanks for filing this issue. This cookbook isn't intended to be a general purpose APT/YUM cookbook. It's mostly geared toward interacting with the packagecloud API to issue read tokens and install GPG keys.

If you can expand a bit on the use case and why this would be a useful addition to this cookbook, we'll certainly consider it.

**Comment by marcusn** [comment]
Sure. 

There are several third party cookbooks that uses packagecloud cookbook. To use those cookbooks in a firewalled environment (prod is not allowed to use internet) , we need those cookbooks to use local mirrors. There are essentially two ways I can think of:

1.  In the wrapper for the third party cookbook, modify the packagecloud resource using chef rewind. This has to be done in every wrapper. 
2. Override baseurl globally in a base cookbook. 

I prefer 2 as it can be done generally and once, and it less complicated. Thus, this pull request.
