### ISSUE TITLE
resources/repo.rb:10: warning: constant ::Fixnum is deprecated

### ISSUE THREAD

**Issue by rmoriz** [sous-chefs/packagecloud#52]
Ruby 2.4 deprecation warning.

See http://blog.bigbinary.com/2016/11/18/ruby-2-4-unifies-fixnum-and-bignum-into-integer.html

=> `::Integer`

**Comment by tas50** [comment]
Fixed in https://github.com/computology/packagecloud-cookbook/pull/53

**Comment by martinisoft** [comment]
My PR also closes this, but upgrades to Chef 12+ in the process.
